sylius_ui:
    # TODO
#    events:
#        sylius.shop.layout.javascripts:
#            blocks:
#                threebrs_sylius.sylius_packeta_plugin.shop.layout.javascripts:
#                    template: "@ThreeBRSSyliusPacketaPlugin/Shop/_javascripts.html.twig"
#                    priority: 5

sylius_resource:
    resources:
        threebrs_packeta_plugin.packeta_config:
            driver: doctrine/orm
            classes:
                model: ThreeBRS\SyliusPacketaPlugin\Entity\PacketaConfig
                repository: ThreeBRS\SyliusPacketaPlugin\Repository\PacketaConfigRepository
                form: ThreeBRS\SyliusPacketaPlugin\Form\Type\PacketaConfigType
