sylius_resource:
    resources:
        threebrs_packeta_plugin.packeta_config:
            driver: doctrine/orm
            classes:
                model: ThreeBRS\SyliusPacketaPlugin\Entity\PacketaConfig
                repository: ThreeBRS\SyliusPacketaPlugin\Repository\PacketaConfigRepository
                form: ThreeBRS\SyliusPacketaPlugin\Form\Type\PacketaConfigType
