parameters:
    shippingMethodsCodes: ['packeta']
    threebrs_sylius_packeta_plugin_payment_methods: ['cz', 'pl', 'sk', 'hu', 'ro']

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ThreeBRS\SyliusPacketaPlugin\Form\Extension\ShipmentPacketaExtension:
        arguments:
            - '@sylius.resolver.shipping_methods.default'
            - '@sylius.repository.shipping_method'
            - '@translator'
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType

    ThreeBRS\SyliusPacketaPlugin\Form\Extension\AdminPacketaShippingMethodExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodType

    ThreeBRS\SyliusPacketaPlugin\Form\Type\PacketaConfigType:
        tags:
            - name: form.type
        arguments:
            $countryChoices: '%threebrs_sylius_packeta_plugin_payment_methods%'
            $dataClass: ThreeBRS\SyliusPacketaPlugin\Entity\PacketaConfig
            $validationGroups: ['sylius']

    ThreeBRS\SyliusPacketaPlugin\Model\PacketaShipmentExporter:
        public: true
        arguments:
            $currencyConverter: '@sylius.converter.currency'
            $shippingMethodsCodes: '%shippingMethodsCodes%'
        tags:
            - name: threebrs.shipment_exporter_type
              type: 'packeta'
              label: 'Packeta'
