sylius_twig_hooks:
    hooks:
        'sylius_shop.shared.order.show.summary.addresses.shipping.body':
            address:
                template: "@ThreeBRSSyliusPacketaPlugin/Shop/shared/address/shipping_address.html.twig"
                priority: 0
