sylius_twig_hooks:
    hooks:
        'sylius_shop.checkout.select_shipping.content.form.shipments.shipment.choice.details':
            packeta:
                template: '@ThreeBRSSyliusPacketaPlugin/Shop/checkout/select_shipping/content/form/shipments/shipment/choice/packeta.html.twig'
                priority: 0

        'sylius_shop.checkout.select_shipping':
            3brs_packeta_javascript:
                template: '@ThreeBRSSyliusPacketaPlugin/Shop/checkout/select_shipping/javascript/packeta_javascript.html.twig'
                priority: -100
